// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyytB8-RLpi87RlyBrAQ42TXwxsNd8itQ',
    appId: '1:539314474969:web:33ef6a71e71b1c6c32d3c8',
    messagingSenderId: '539314474969',
    projectId: 'kngro-de758',
    authDomain: 'kngro-de758.firebaseapp.com',
    storageBucket: 'kngro-de758.appspot.com',
    measurementId: 'G-275LXFNY8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ZoNp-LK3f0je0gfi7EMud6J-dsanEjo',
    appId: '1:539314474969:android:e027190d3937e51632d3c8',
    messagingSenderId: '539314474969',
    projectId: 'kngro-de758',
    storageBucket: 'kngro-de758.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ7sBhmIuI8UMg_2blaCq0LnBUx4yt98c',
    appId: '1:539314474969:ios:00f84cd0329aeabd32d3c8',
    messagingSenderId: '539314474969',
    projectId: 'kngro-de758',
    storageBucket: 'kngro-de758.appspot.com',
    iosBundleId: 'network.mining.kngro',
  );
}
